# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rZ5jxCGEwsC9ShIp8sRsuGf1S8na9Jl0
"""

def calculate_electricity_bill(units):
  bill=0
  if units<=100:
    bill=units*2
  elif units<=200:
    bill=(100*2)+((units-100)*4)
  else:
    bill=(100*2)+(100*4)+((units-200)*6)
  return bill
unit=int(input("enter units"))
bill=calculate_electricity_bill(unit)
print(bill)