# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QNV5Ggv4xhB3EnZwo5JOdj4FUu87ngR9
"""

#intern eligibility evaluation
def check_intern(age,per):
  age=int(input("enter the age"))
  per=int(input("enter the percentage"))
  if (age>=18):
    if (per>=60):
      return "Eligible"
    else:
      return ("not Eligible")
result=check_intern(age,per)
print(result)