# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rZ5jxCGEwsC9ShIp8sRsuGf1S8na9Jl0
"""

def calculate_discount(price,customer_type):
  if customer_type == "Regular":
    discount =0.05
  elif customer_type == "premium":
    discount = 0.15
  elif customer_type == "employee":
    discount = 0.25
  else:
    discount = 0
  Total_price = price-(price*discount)
  return Total_price
print(calculate_discount(100,"premium"))
print(calculate_discount(100,"Regular"))
print(calculate_discount(1000,"employee"))