# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Hkk5JmHH3-xDGwfSWyZjzXYVIs73Z3S
"""

Amount=int(input("Enter the amount"))
if Amount>0:
  print("Valid Purchase amount")
else:
  print("Invalid Purchase amount")

