# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Hkk5JmHH3-xDGwfSWyZjzXYVIs73Z3S
"""

Amount=int(input("Enter the amount"))
if Amount>0:
  print("Valid Purchase amount")
else:
  print("Invalid Purchase amount")

opening_stock=[45,65,34,78]
closing_stock=[32,65,56,67]
for i in range(len(opening_stock)):
  if opening_stock[i]<closing_stock[i]:
    print("product",i+1,"stock increased")
  elif opening_stock[i]>closing_stock[i]:
    print("product",i+1,"stock decreased")
  else:
    print("product",i+1,"stock not changed")

students={
    "asha":"python",
    "ravi":"data analytics",
    "neha":"AI"
}
print("students name:")
for name in students.keys():
  print(name)
print("courses:")
for course in students.values():
  print(course)
student_name=input("enter the student name:")
if student_name in students:
  print("student name:",student_name)
else:
  print("student not found")

distance=float(input("enter the distance="))
if distance<=5:
  print("Local delivery")
elif distance<=20:
  print("City delivery")
else:
  print("Outstanding delivery")