# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Hkk5JmHH3-xDGwfSWyZjzXYVIs73Z3S
"""

scores=[90,45,60,70,50,30]
total_score=sum(scores)
average_score=total_score/len(scores)
above_average_count=0
for score in scores:
  if score>average_score:
    above_average_count+=1
print("scores",scores)
print("total score:",total_score)
print("average score:",average_score)
print("above average count:",above_average_count)

product_prices=(100,200,300,400,500)
print("product prices:",product_prices)
product_prices[1]=600
print("First product price:",product_prices[0])
print("Second product price:",product_prices[2])



Amount=int(input("Enter the amount"))
if Amount>0:
  print("Valid Purchase amount")
else:
  print("Invalid Purchase amount")

opening_stock=[45,65,34,78]
closing_stock=[32,65,56,67]
for i in range(len(opening_stock)):
  if opening_stock[i]<closing_stock[i]:
    print("product",i+1,"stock increased")
  elif opening_stock[i]>closing_stock[i]:
    print("product",i+1,"stock decreased")
  else:
    print("product",i+1,"stock not changed")



students={
    "asha":"python",
    "ravi":"data analytics",
    "neha":"AI"
}
print("students name:")
for name in students.keys():
  print(name)
print("courses:")
for course in students.values():
  print(course)
student_name=input("enter the student name:")
if student_name in students:
  print("student name:",student_name)
else:
  print("student not found")

distance=float(input("enter the distance="))
if distance<=5:
  print("Local delivery")
elif distance<=20:
  print("City delivery")
else:
  print("Outstanding delivery")