# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EI0dRJf4Tq_yNfaRv8MsYz-LiJOgLLi6
"""

item_prices=[500,350,900,600,250,700]
total_order_values=sum(item_prices)
average = total_order_values/len(item_prices)
print("Total Order Value=",total_order_values)
print("Average item price=",average)

Products={
    "Laptop":"Electronics",
    "Chair":"Furniture",
    "Mobile":"Electronics"
}
for Product in Products.keys():
  print("Product name:",Product)

for Category in Products.values():
  print("Categories :",Category)
print(len(Products))

